spring.application.name=ProyectoFianal_Integrador
spring.datasource.url=jdbc:mysql://localhost:3306/bd_integrador
spring.datasource.username=root
spring.datasource.password=74418228

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8083

