INSERT INTO productos (nombre, precio, imagen_url, categoria, descripcion) VALUES
('Promo Familiar', 79.00, 'secciones/promociones/Promocion1.png', 'Promociones', '1 Pollo + Papas fritas + Ensalada + Tequeños'),
('Promo Gaseosa', 89.00, 'secciones/promociones/Promocion2.png', 'Promociones', '1 Pollo + Papas + Ensalada + Gaseosa 1L'),
('Promo Peruana', 92.00, 'secciones/promociones/Promocion3.png', 'Promociones', '1 Pollo + Papas + Ensalada + Chicha 1.5L'),
('Promo Dúo', 49.00, 'secciones/promociones/promocion4.png', 'Promociones', '1/2 Pollo + Papas + Ensalada + 2 Gaseosas 500ml'),
('Promo Mega Familiar', 159.00, 'secciones/promociones/promocion5.png', 'Promociones', '2 Pollos + 2 Papas + 2 Ensaladas + Gaseosa 1.5L'),
('1/4 Pollo (Pierna)', 25.00, 'secciones/pollos/1-4pollo.png', 'Pollos', 'Papas fritas y ensalada.'),
('1/4 Pollo (Pecho)', 27.00, 'secciones/pollos/1-4pollopecho.png', 'Pollos', 'Papas fritas y ensalada.'),
('1/2 Pollo', 45.00, 'secciones/pollos/1-2pollo.png', 'Pollos', 'Papas fritas y ensalada.'),
('1 Pollo', 79.00, 'secciones/pollos/1-pollo.png', 'Pollos', 'Papas fritas y ensalada.'),
('Alitas BBQ (6 und.)', 25.00, 'secciones/piqueos/alitas_bbq.png', 'Piqueos', 'Alitas bañadas en salsa BBQ.'),
('Alitas Buffalo (6 und.)', 25.00, 'secciones/piqueos/alitas_buffalo.png', 'Piqueos', 'Alitas picantes estilo Buffalo.'),
('Nuggets de Pollo', 20.00, 'secciones/piqueos/nuggets_pollo.png', 'Piqueos', 'Crujientes nuggets de pollo.'),
('Tequeños de Queso', 18.00, 'secciones/piqueos/tequenos_queso.png', 'Piqueos', 'Tequeños artesanales de queso.'),
('Salchipapa Brasa', 24.00, 'secciones/piqueos/salchipapa_brasa.png', 'Piqueos', 'Con trozos de pollo a la brasa.'),
('Hamburguesa Clásica', 20.00, 'secciones/hamburguesas/hamburguesa_clasica.png', 'Hamburguesas', 'Hamburguesa clásica.'),
('Hamburguesa con Tocino', 23.00, 'secciones//hamburguesas/hamburguesa_tocino.png', 'Hamburguesas', 'Con tocino crocante.'),
('Hamburguesa Crispy Chicken', 24.00, 'secciones/hamburguesas/hamburguesa_crispy_chicken.png', 'Hamburguesas', 'Pollo crujiente.'),
('Hamburguesa Doble Carne', 28.00, 'secciones/hamburguesas/hamburguesa_doble_carne.png', 'Hamburguesas', 'Doble carne jugosa.'),
('Wrap de Pollo a la Brasa', 18.00, 'secciones/Warp/wrap_pollo_brasa.png', 'Wraps', 'Pollo a la brasa en tortilla.'),
('Crispy Chicken Wrap', 19.00, 'secciones/Warp/crispy_chicken_wrap_v2.png', 'Wraps', 'Pollo crispy en tortilla.'),
('Bacon Cheese Wrap', 20.00, 'secciones/Warp/bacon_cheese_wrap.png', 'Wraps', 'Tocino y queso en tortilla.'),
('Papas fritas chicas', 8.00, 'secciones/Acompañamientos/papas_chicas_v2.png', 'Acompañamientos', 'Porción individual.'),
('Papas fritas familiares', 15.00, 'secciones/Acompañamientos/papas_familiares.png', 'Acompañamientos', 'Porción para compartir.'),
('Arroz con choclo', 10.00, 'secciones/Acompañamientos/arroz_con_choclo.png', 'Acompañamientos', 'Arroz con choclo tierno.'),
('Onion Rings', 16.00, 'secciones/Acompañamientos/onion_rings.png', 'Acompañamientos', 'Aros de cebolla.'),
('Camote frito', 14.00, 'secciones/Acompañamientos/camote_frito_premium.png', 'Acompañamientos', 'Camotes crocantes.'),
('Brownie', 8.00, 'secciones/postres/brownie_fudge.png', 'Postres', 'Chocolate fudge.'),
('Picarones', 15.00, 'secciones/postres/picarones.png', 'Postres', 'Con miel de chancaca.'),
('Tres Leches', 10.00, 'secciones/postres/tres_leches.png', 'Postres', 'Bizcocho tres leches.'),
('Gaseosa 500 ml', 5.00, 'secciones/Bebidas/gaseosas_personales.png', 'Bebidas', 'Gaseosa personal.'),
('Gaseosa 1 L', 9.00, 'secciones/Bebidas/gaseosa_1L.png', 'Bebidas', 'Gaseosa 1 Litro.'),
('Gaseosa 1.5 L', 12.00, 'secciones/Bebidas/Gaseosa1.5L.png', 'Bebidas', 'Gaseosa 1.5 Litros.'),
('Chicha Morada 1.5 L', 14.00, 'secciones/Bebidas/chicha_morada_1.5L.png', 'Bebidas', 'Chicha artesanal.');